spring:
  profiles:
    active:
    - dev
---
server:
  port: 8761  #注册中心占用8761端口，冒号后面必须要有空格
spring:
  profiles: dev    #开发环境
  application:
    name: ecp-config-eureka-client
    
eureka:
  instance:
    hostname: eureka-ecp.com  #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka-ecp.com:8761/eureka/
---
server:
  port: 8762 #注册中心占用8762端口，冒号后面必须要有空格
  
spring:
  profiles: test    #测试环境
  application:
    name: ecp-config-eureka-client

eureka:
  instance:
    hostname: eureka-ecp.com  #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka-ecp.com:8762/eureka/